import { test as base, type Page } from '@playwright/test';

/**
 * Extends the base test fixture to pre-enable demo mode via localStorage.
 * All dashboard tests should use this fixture so they skip the login gate
 * and get deterministic demo data without a backend.
 */
export const test = base.extend<{ demoPage: Page }>({
  demoPage: async ({ page }, use) => {
    // Seed localStorage before any navigation so the DemoModeProvider
    // picks it up on first render.
    await page.addInitScript(() => {
      localStorage.setItem('qod-demo-mode', 'true');
    });
    await use(page);
  },
});

export { expect } from '@playwright/test';

/** Demo project IDs generated by the shared demo-data provider. */
export const DEMO_PROJECTS = {
  ecommerce: { id: 'demo-ecommerce', name: 'E-Commerce Platform' },
  banking: { id: 'demo-banking', name: 'Mobile Banking App' },
  internal: { id: 'demo-internal', name: 'Internal Tools' },
} as const;
